[[repos]]
repo = "builtin"
hooks = [
  { id = "check-added-large-files", priority = 0 },
  { id = "check-case-conflict", priority = 0 },
  { id = "check-executables-have-shebangs", priority = 0 },
  { id = "check-illegal-windows-names", priority = 0 },
  { id = "check-json", priority = 0 },
  { id = "check-json5", priority = 0 },
  { id = "check-merge-conflict", args = ["--assume-in-merge"], priority = 0 },
  { id = "check-shebang-scripts-are-executable", priority = 0 },
  { id = "check-symlinks", priority = 0 },
  { id = "check-toml", priority = 0 },
  { id = "check-vcs-permalinks", priority = 0 },
  { id = "check-xml", priority = 0 },
  { id = "check-yaml", priority = 0 },
  { id = "destroyed-symlinks", priority = 0 },
  { id = "detect-private-key", priority = 0 },
  { id = "end-of-file-fixer" },
  { id = "fix-byte-order-marker" },
  { id = "mixed-line-ending" },
  { id = "trailing-whitespace" },
]

[[repos]]
repo = "https://github.com/asottile/pyupgrade"
rev = "v3.21.2"
hooks = [
  { id = "pyupgrade", args = ["--py314-plus"] },
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.11"
hooks = [
  { id = "ruff-check", args = ["--fix"] },
  { id = "ruff-format" },
]

[[repos]]
repo = "https://github.com/DetachHead/basedpyright-prek-mirror"
rev = "1.39.3"
hooks = [
  { id = "basedpyright", priority = 99 },
]

[[repos]]
repo = "https://github.com/tombi-toml/tombi-pre-commit"
rev = "v0.9.22"
hooks = [
  { id = "tombi-format" },
  { id = "tombi-lint", priority = 99 },
]
